// <auto-generated />
using System;
using Elevator.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Elevator.Data.Migrations
{
    [DbContext(typeof(ElevatorDbContext))]
    [Migration("20240929182659_AddThreadId")]
    partial class AddThreadId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Elevator.Data.Entities.dbElevator", b =>
                {
                    b.Property<int?>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("CarId"));

                    b.Property<string>("CarName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CurrentFloor")
                        .HasColumnType("int");

                    b.HasKey("CarId");

                    b.ToTable("DbElevators");
                });

            modelBuilder.Entity("Elevator.Data.Entities.dbElevatorProgress", b =>
                {
                    b.Property<int?>("ProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("ProgressId"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentDirection")
                        .HasColumnType("int");

                    b.Property<string>("CurrentFloorsQueued")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("int");

                    b.Property<string>("ManageThreadId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProgressId");

                    b.ToTable("DbElevatorProgress");
                });

            modelBuilder.Entity("Elevator.Data.Entities.dbElevatorRequest", b =>
                {
                    b.Property<int?>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("RequestId"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("RequestedDirection")
                        .HasColumnType("int");

                    b.Property<string>("RequestedFloors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestedFromFloor")
                        .HasColumnType("int");

                    b.HasKey("RequestId");

                    b.ToTable("DbElevatorsRequest");
                });
#pragma warning restore 612, 618
        }
    }
}
